fix: 加载话题时出错
用户名为null:

JsonDecodingException: Unexpected JSON token at offset 5375: Unexpected 'null' value instead of string literal at path:
    $.data.relate_thread.thread_list[0].thread_info.author.name